version: "3"

services:
  webserver:
    image: betagouv/kelrisks-data-preparation:$BRANCH-latest
    network_mode: host
    environment:
      AIRFLOW__CORE__FERNET_KEY: $AIRFLOW__CORE__FERNET_KEY
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
      AIRFLOW__CORE__DAG_CONCURRENCY: $AIRFLOW__CORE__DAG_CONCURRENCY
      AIRFLOW_CONN_POSTGRES_KELRISKS: "postgresql+psycopg2://$KELRISKS_POSTGRES_USER:$KELRISKS_POSTGRES_PASSWORD@$KELRISKS_POSTGRES_HOST:$KELRISKS_POSTGRES_PORT/$KELRISKS_POSTGRES_DB"
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: $PORT
      AIRFLOW__WEBSERVER__WEB_SERVER_HOST: "127.0.0.1"
      AIRFLOW__WEBSERVER__WORKERS: $AIRFLOW__WEBSERVER__WORKERS
      POSTGRES_HOST: $POSTGRES_HOST
      KELRISKS_POSTGRES_HOST: $KELRISKS_POSTGRES_HOST
      KELRISKS_POSTGRES_PORT: $KELRISKS_POSTGRES_PORT
      KELRISKS_POSTGRES_USER: $KELRISKS_POSTGRES_USER
      KELRISKS_POSTGRES_PASSWORD: $KELRISKS_POSTGRES_PASSWORD
      KELRISKS_POSTGRES_DB: $KELRISKS_POSTGRES_DB
      KELRISKS_POSTGRES_SSL_ON: $KELRISKS_POSTGRES_SSL_ON
      DEPARTEMENTS: $DEPARTEMENTS
