version: '3.1'

services:
  db:
    build: postgres
    restart: always
    ports:
      - "5432:5432"
    # env_file:
    # - ./dev.env
    volumes:
    - ./data/postgres:/var/lib/postgresql/data
    - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
