version: "3"

services:
  webserver:
    image: betagouv/kelrisks-data-preparation:$BRANCH-latest
    network_mode: host
    ports:
      - 127.0.0.1:$PORT:8080
    environment:
      AIRFLOW__CORE__FERNET_KEY: $AIRFLOW__CORE__FERNET_KEY
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW_CONN_POSTGRES_KELRISKS: "postgresql+psycopg2://$KELRISKS_POSTGRES_USER:$KELRISKS_POSTGRES_PASSWORD@$KELRISKS_POSTGRES_HOST:$KELRISKS_POSTGRES_PORT/$KELRISKS_POSTGRES_DB"
      POSTGRES_HOST: $POSTGRES_HOST
      KELRISKS_POSTGRES_HOST: $KELRISKS_POSTGRES_HOST
      KELRISKS_POSTGRES_PORT: $KELRISKS_POSTGRES_PORT
      KELRISKS_POSTGRES_USER: $KELRISKS_POSTGRES_USER
      KELRISKS_POSTGRES_PASSWORD: $KELRISKS_POSTGRES_PASSWORD
      KELRISKS_POSTGRES_DB: $KELRISKS_POSTGRES_DB
      KELRISKS_POSTGRES_SSL_ON: $KELRISKS_POSTGRES_SSL_ON
      CADASTRE_CONCURRENCY: $CADASTRE_CONCURRENCY
      DEPARTEMENTS: $DEPARTEMENTS
