version: "3"

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - pg_data:/var/lib/postgresql/data

  webserver:
    image: webserver
    build:
      context: ./code
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 127.0.0.1:$PORT:8080
    volumes:
      - ./code/dags:/usr/local/airflow/dags
      - ./code/embulk:/usr/local/airflow/embulk
      - ./code/templates:/usr/local/airflow/templates
      - ./code/sql:/usr/local/airflow/sql
    environment:
      AIRFLOW__CORE__FERNET_KEY: $AIRFLOW__CORE__FERNET_KEY
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW_CONN_POSTGRES_KELRISKS: "postgresql+psycopg2://$KELRISKS_POSTGRES_USER:$KELRISKS_POSTGRES_PASSWORD@$KELRISKS_POSTGRES_HOST:$KELRISKS_POSTGRES_PORT/$KELRISKS_POSTGRES_DB"
      POSTGRES_HOST: $POSTGRES_HOST
      KELRISKS_POSTGRES_HOST: $KELRISKS_POSTGRES_HOST
      KELRISKS_POSTGRES_PORT: $KELRISKS_POSTGRES_PORT
      KELRISKS_POSTGRES_USER: $KELRISKS_POSTGRES_USER
      KELRISKS_POSTGRES_PASSWORD: $KELRISKS_POSTGRES_PASSWORD
      KELRISKS_POSTGRES_DB: $KELRISKS_POSTGRES_DB
      KELRISKS_POSTGRES_SSL_ON: $KELRISKS_POSTGRES_SSL_ON
      CADASTRE_CONCURRENCY: $CADASTRE_CONCURRENCY
      DEPARTEMENTS: $DEPARTEMENTS

volumes:
  pg_data:
