 version: 2.1
 jobs:
   build:
     docker:
       - image: docker
     steps:
       - checkout
       - setup_remote_docker
       - run: |
          docker build -t betagouv/kelrisks-data-preparation-webserver:$CIRCLE_SHA1 ./code