version: 2.1

jobs:
  build:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t betagouv/kelrisks-data-preparation:$CIRCLE_SHA1 ./code
          docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
          docker push betagouv/kelrisks-data-preparation:$CIRCLE_SHA1
          docker tag betagouv/kelrisks-data-preparation:$CIRCLE_SHA1 betagouv/kelrisks-data-preparation:${CIRCLE_BRANCH}-latest
          docker push betagouv/kelrisks-data-preparation:${CIRCLE_BRANCH}-latest
  deploy:
    machine:
      enabled: true
    parameters:
      user:
        type: env_var_name
        default: SSH_USER
      host:
        type: env_var_name
        default: SSH_HOST
      branch:
        type: env_var_name
        default: CIRCLE_BRANCH
    steps:
      - checkout
      - run:
          command: |
              ssh ${<< parameters.user >>}@${<< parameters.host >>} "cd /srv/kelrisks-data-preparation/
              if ${<< parameters.user >>} == "master"; then cd prod; else cd preprod; fi;
              git pull"

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - dev
      - deploy:
          filters:
            branches:
              only:
                - master
                - dev
          requires:
            - build